Fix license classifier
gurumitts/pylutron-caseta pull request #168
Opened 2024-06-24 15:39 UTC by joostlek

Hey 👋🏻,

I am currently looking into licensing at Home Assistant, and I found that we could not detect the license of this library properly. According to pyproject.toml documentation about the `license` field:
> If you are using a standard, well-known license, it is not necessary to use this field. Instead, you should use one of the [classifiers](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#classifiers) starting with License ::. (As a general rule, it is a good idea to use a standard, well-known license, both to avoid confusion and because some organizations avoid software whose license is unapproved.)

If you could do a release after this PR, that would be awesome :)

2024-06-24 15:40 UTC, joostlek commented
Also, please consider adding a LICENSE file to the root of the project so its easier to see that its OSI approved

2024-06-24 22:16 UTC, mdonoughe requested changes
This PR changes the license of the project.

This project is licensed under the Apache-2.0 license, and that is [correctly specified](https://hatch.pypa.io/1.9/config/metadata/#license) in the pyproject.toml file and package metadata. `License :: OSI Approved :: Apache Software License` is one of the old classifiers on the [PEP 639 blacklist](https://peps.python.org/pep-0639/appendix-mapping-classifiers/#spec-mapping-classifiers-identifiers).

I guess if they're both specified it's clear what the real license is, and since the classifier name contains "OSI Approved" it's one of the OSI approved versions of Apache so that's probably good enough, but a Home Assistant license check script should understand PEP 639 license metadata because at least Poetry and Hatch recommend using standard SPDX licenses (PEP 639) instead of Python classifiers. It looks like Poetry will add this ambiguous classifier, but Hatch doesn't add license classifiers.

2024-07-04 19:56 UTC, mdonoughe approved these changes

2024-07-04 20:05 UTC, merged

2024-07-05 07:47 UTC, joostlek commented
Thanks for wrapping it up. I didn't completely understand what direction you wanted to go in. But much appreciated 😊